FROM node:latest
LABEL Drew Durham (coledurham@gmail.com)
LABEL project=blackjack
LABEL tag=base
WORKDIR /app/code
COPY code/package-base.json package.json
RUN npm install --ignore-scripts
EXPOSE 3000
CMD ["bash"]