version: "3.3"
services:
    web:
      image: terraform.local/srv/blackjack:local
      env_file:
        - .env
      ports:
        - "4001:3000"
      networks:
        - blackjack-net 
      volumes:
          - blackjack:/blackjack/data
          
networks:
  blackjack-net:
    driver: bridge

volumes:
  blackjack:
